# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'monthly'
      day: 'wednesday'
      time: '10:00'
      timezone: 'Europe/Berlin'
    assignees: ['born3am'] # Assign PRs to a specific user or team
    commit-message:
      prefix: 'chore' # PR title prefix
      include: 'scope'
    groups:
      minor-updates:
        applies-to: version-updates
        update-types:
          - 'patch' # Group all patch updates together
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '*'
        versions:
          - 'alpha'
          - 'beta'
          - 'canary'
          - 'dev'
          - 'experimental'
          - 'legacy'
          - 'next'
          - 'nightly'
